apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: apache-airflow
spec:
  interval: 30s
  releaseName: airflow-staging
  chart:
    spec:
      chart: airflow
      version: "1.7.0"
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: flux-system
  values:
    defaultAirflowTag: "2.5.1"
    airflowVersion: "2.5.1"
    fernetKey: "zTxhk7FuGqQVPZVoukLn5bGWOrgHzhQnBnaqAItcZGI="
    env:
      - name: "AIRFLOW__CORE__LOAD_EXAMPLES"
        value: "False"
      - name: "AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE"
        value: "apache-airflow"
      - name: "AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_REPOSITORY"
        value: "apache/airflow"
      - name: "AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_TAG"
        value: "2.5.1-python3.10"
    executor: "KubernetesExecutor"
    postgresql:
      enabled: false
    data:
      metadataConnection:
        user: "airflow_user"
        password: "BvVx4cPH5S6O"
        host: "stride-dev.c72ywm0ekmo1.ap-south-1.rds.amazonaws.com"
        port: 3306
        db: "airflow_db"
    export AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'mysql+mysqlclient://airflow_user:BvVx4cPH5S6O@stride-dev.c72ywm0ekmo1.ap-south-1.rds.amazonaws.com:3306/airflow_db'
    createUserJob:
      useHelmHooks: false
    migrateDatabaseJob:
      useHelmHooks: false
    web: